meetboard/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings

from mb_auth.views import loginView, logoutView
from meetings.views import Home


urlpatterns = [
    path('', Home, name='home'),
    path('login/', loginView, name='login'),
    path('logout/', logoutView, name='logout'),
    path('meet/', include(('meetings.urls', 'meetings'), namespace='meetings')),
    path('proto/', include(('protocols.urls', 'protocols'), namespace='protocols')),
    path('admin/', admin.site.urls, name='admin'),
]

meetings/urls.py
from django.contrib import admin
from django.urls import path
from meetings import views

urlpatterns = [
    path('table/', views.meet_table, name='table'),
    path('add/', views.meet_update, name='add'),
    path('update/<str:meet_id>/', views.meet_update, name='update'),
    path('delete/<str:meet_id>/', views.meet_delete, name='delete'),
    path('copy/<str:meet_id>/', views.meet_copy, name='copy'),
    path('membersupd/', views.members_update, name='membersupd'),
    path('membersget/<str:meet_id>/', views.members_get, name='membersget'),
    path('membersdoc/<str:meet_id>/', views.members_doc, name='membersdoc'),
    path('itemsupd/', views.items_update, name='itemsupd'),
    path('itemsget/<str:meet_id>/', views.items_get, name='itemsget'),
    path('itemsdoc/<str:meet_id>/', views.items_doc, name='itemsdoc'),
    path('studiosupd/', views.studios_update, name='studiosupd'),
    path('studiosget/<str:meet_id>/', views.studios_get, name='studiosget'),
    path('studiosget_bydep/<str:dep_id>/', views.studios_get_bydep, name='studiosget_bydep'),
    path('studiosdoc/<str:meet_id>/', views.studios_doc, name='studiosdoc'),
    path('plandoc/', views.plan_doc, name='plandoc'),
    # path('checksget/<str:meet_id>/', views.checks_get, name='checksget'),
    path('checksupd/<str:meet_id>/', views.checks_update, name='checksupd'),
]

meetings/models.py
from django.db import models
from django.forms import ModelForm
from django.utils import timezone

mVideo = 'V'
mAudio = 'A'
mInternal = 'I'

MEETING_TYPE_CHOICES = (
    (mVideo, 'Видео конференция'),
    (mAudio, 'Аудио селектор'),
    (mInternal, 'Очное совещание'),
)

STUDIO_TYPE_CHOICES = (
    (mVideo, 'Видео'),
    (mAudio, 'Аудио'),
)

class Meeting(models.Model):
    meet_type = models.CharField(max_length=1, choices=MEETING_TYPE_CHOICES, default=mInternal)
    meet_subj = models.CharField(max_length=128, db_index=True)
    meet_date = models.DateField(null=False, default=timezone.now)
    meet_start = models.CharField(max_length=5,null=True)
    meet_end = models.CharField(max_length=5,null=True)
    meet_acc = models.CharField(max_length=64, db_index=True, blank=True)
    meet_tel = models.CharField(max_length=20, blank=True)
    meet_save = models.BooleanField(default=False)
    meet_confident = models.BooleanField(default=False)
    studios = models.ManyToManyField('Studio', through='StudioList')

    class Meta:
        verbose_name = 'Совещание'
        verbose_name_plural = 'Совещания'

    def __str__(self):
         return  str(self.meet_date) +' | '+ self.meet_subj

class Member(models.Model):
    meeting = models.ForeignKey('Meeting', db_index=True, null=True, on_delete=models.CASCADE)
    dep = models.CharField(max_length=64, db_index=True, default='')
    f = models.CharField(max_length=32,db_index=True)
    i = models.CharField(max_length=32, db_index=True)
    o = models.CharField(max_length=32, db_index=True, blank=True)
    fio = models.CharField(max_length=64, db_index=True)
    dol = models.CharField(max_length=128, db_index=True)
    is_speaker = models.IntegerField(default=0)
    is_lead = models.IntegerField(default=0)
    is_init = models.IntegerField(default=0)
    is_presence = models.IntegerField(default=0)
    order_n = models.PositiveIntegerField(null=False, default=0)

    def __str__(self):
         return  self.fio

class Employee(models.Model):
    dep = models.ForeignKey('Dep', db_index=True, null=True, on_delete=models.SET_NULL, verbose_name='Организация')
    f = models.CharField(max_length=32,db_index=True, verbose_name='Фамилия')
    i = models.CharField(max_length=32, db_index=True, verbose_name='Имя')
    o = models.CharField(max_length=32, db_index=True, blank=True, verbose_name='Отчество')
    dol = models.CharField(max_length=128, db_index=True, verbose_name='Должность')
    email = models.EmailField(verbose_name='E-Mail', blank=True)
    tel = models.CharField(max_length=16, verbose_name='Телефон', blank=True)

    def __str__(self):
         return  self.f+' '+self.i+' '+self.o+' '

    class Meta:
        verbose_name = 'Сотрудник'
        verbose_name_plural = 'Сотрудники'

class Dep(models.Model):
    name = models.CharField(max_length=64, db_index=True, verbose_name='Организация')

    class Meta:
        verbose_name = 'Организацию'
        verbose_name_plural = 'Организации'

    def __str__(self):
        return self.name

class Studio(models.Model):
    dep = models.ForeignKey('Dep', db_index=True, null=True, on_delete=models.SET_NULL, verbose_name='Организация')
    studio_addr = models.CharField(max_length=256, db_index=True, verbose_name='Адрес студии')
    studio_type = models.CharField(max_length=1, choices=STUDIO_TYPE_CHOICES, default=mVideo, verbose_name='Тип студии')

    class Meta:
        verbose_name = 'Студию'
        verbose_name_plural = 'Студии'

    def __str__(self):
        return self.dep.name+' / '+self.studio_addr+' / '+self.studio_type

class StudioList(models.Model):
    meeting = models.ForeignKey('Meeting', db_index=True, null=True, on_delete=models.CASCADE)
    studio = models.ForeignKey('Studio', db_index=True, null=True, on_delete=models.CASCADE)
    order_n = models.PositiveIntegerField(null=False, default=0)

class Item(models.Model):
    meeting = models.ForeignKey('Meeting', db_index=True, null=True, on_delete=models.CASCADE)
    item_subj = models.CharField(max_length=256)
    item_time = models.CharField(max_length=16, db_index=True)
    dep = models.CharField(max_length=64, db_index=True, default='')
    f = models.CharField(max_length=32,db_index=True)
    i = models.CharField(max_length=32, db_index=True)
    o = models.CharField(max_length=32, db_index=True, blank=True)
    dol = models.CharField(max_length=128, db_index=True)
    order_n = models.PositiveIntegerField(null=False, default=0)

    def __str__(self):
        return self.item_subj+' / '+self.item_time

class Check(models.Model):
    meeting = models.ForeignKey('Meeting', on_delete=models.CASCADE, db_index=True, unique=True)
    data = models.TextField(default="")
    complete = models.IntegerField(default=0)
    total = models.IntegerField(default=1)

meetings/views.py
import datetime
import json
import os
from docxtpl import DocxTemplate

from django.template.context_processors import csrf
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.db.models import Count, F, Q
from django.utils import timezone

from mb_auth.views import mb_login

from meetings.models import MEETING_TYPE_CHOICES, Meeting, Dep, Member, Item, Studio, StudioList, Employee, Check

@mb_login(url='login')
def Home(request):
    args={}
    args['meetings'] = Meeting.objects.filter(meet_date__gte=timezone.now()). \
                           annotate(complete=F('check__complete'),
                                    total=F('check__total'),
                                    progress=(F('check__complete') * 100 /F('check__total') )). \
                           order_by('meet_date', '-meet_start')[0:3]
    return render(request,'mb_home.html', args)

@mb_login(url='login')
def meet_table(request):
    args={}

    args['employees'] = Employee.objects.all().order_by('f','i','o','dol')
    args['meetings'] = Meeting.objects.all().\
        annotate(members_cnt=Count('member'),items_cnt=Count('item'),studios_cnt=Count('studiolist')). \
        annotate(proto_id=F('protocol__id'), proto_n=F('protocol__proto_regnum'), proto_d=F('protocol__proto_regdate'),
                 complete=F('check__complete'),
                 total=F('check__total'),
                 progress=(F('check__complete') * 100 / F('check__total') )). \
        order_by('-meet_date','-meet_start')

    args['deps'] = Dep.objects.all().annotate(studios_cnt=Count('studio')).order_by('name')
    return render(request,'mt_table.html', args)

@mb_login(url='login')
def meet_update(request, meet_id=None):
    args={}
    args.update(csrf(request))
    meet =  None
    try:
        meet_id=int(meet_id)
    except:
        meet_id=None

    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        if request.POST:
            meet_type = request.POST.get('meetType')
            meet_subj = request.POST.get('meetSubj')
            meet_date = request.POST.get('meetDate')
            meet_date = datetime.datetime.strptime(meet_date, '%d.%m.%Y').date()
            meet_start = request.POST.get('meetStart')
            meet_end = request.POST.get('meetEnd')
            meet_acc = request.POST.get('meetAcc')
            meet_tel = request.POST.get('meetTel')
            meet_save = (request.POST.get('meetSave','0') == '1')
            meet_confident = (request.POST.get('meetConfident') == '1')

            # Если произошло копирование совещания, то omt_id содержит ID старого совещания
            try:
                omt_id = request.POST.get('omt_id',0)
            except:
                omt_id=0

            if meet_id:
                Meeting.objects.filter(id=meet_id).update(meet_type=meet_type,meet_subj=meet_subj,
                                       meet_date=meet_date, meet_start=meet_start, meet_end=meet_end,
                                       meet_acc=meet_acc, meet_tel=meet_tel, meet_save=meet_save, meet_confident=meet_confident)
            else:
                meet_id=Meeting.objects.create(meet_type=meet_type,meet_subj=meet_subj,
                                       meet_date=meet_date, meet_start=meet_start, meet_end=meet_end,
                                       meet_acc=meet_acc, meet_tel=meet_tel, meet_save=meet_save, meet_confident=meet_confident).id
                if omt_id:
                    #print('start bulk copy from id={} to id={}'.format(omt_id, meet_id))
                    old_members = Member.objects.filter(meeting_id=omt_id)
                    old_items = Item.objects.filter(meeting_id=omt_id)
                    old_studios = StudioList.objects.filter(meeting_id=omt_id)
                    Member.objects.bulk_create([Member(order_n=i.order_n, f=i.f,i=i.i,o=i.o,dep=i.dep,dol=i.dol,fio=i.fio,
                                                       is_speaker=i.is_speaker, is_presence=i.is_presence, is_init=i.is_init,
                                                       is_lead=i.is_lead, meeting_id=meet_id) for i in old_members])
                    Item.objects.bulk_create([Item(order_n=i.order_n, f=i.f,i=i.i,o=i.o,dep=i.dep,dol=i.dol,
                                                   item_subj=i.item_subj, item_time=i.item_time, meeting_id=meet_id) for i in old_items])
                    StudioList.objects.bulk_create([StudioList(order_n=i.order_n, meeting_id=meet_id, studio_id=i.studio_id) for i in old_studios])

            return redirect(reverse("meetings:table"))

    if meet_id:
        try:
            meet = Meeting.objects.get(id=meet_id)
        except Meeting.DoesNotExist:
            meet = None

    args['employees'] = Employee.objects.all().order_by('f', 'i', 'o').values('f', 'i', 'o','tel')
    args['meet']=meet
    args['meet_id'] = meet_id if meet_id else 0
    args['meeting_type_choices'] = MEETING_TYPE_CHOICES

    return render(request,'mt_meetform.html', args)

@mb_login(url='login')
def meet_delete(request, meet_id=None):
    Meeting.objects.filter(id=meet_id).delete()
    return redirect(reverse("meetings:table"))

def meet_copy(request, meet_id=None):
    args = {}
    omt =  None
    if meet_id:
        try:
            omt = Meeting.objects.get(id=int(meet_id))
        except Meeting.DoesNotExist:
            omt = None

    args['employees'] = Employee.objects.all().order_by('f', 'i', 'o').values('f', 'i', 'o', 'tel')
    args['meet']=omt
    args['meet_id'] = None
    args['meeting_type_choices'] = MEETING_TYPE_CHOICES

    return render(request,'mt_meetform.html', args)

@mb_login(url='login')
def members_update(request):
    res = 1
    if request.method == 'POST':
        if request.POST:
            #print(request.POST)
            res = 0
            id_list = []
            meet_id = int(request.POST.get('meet_id',0))
            rowOrder = request.POST.get('membersTable_rowOrder',None)
            if rowOrder and meet_id:
                rowOrder = map(int, rowOrder.split(',')) if rowOrder else None;
                for index, ordern in enumerate(rowOrder):
                    try:
                        id = int(request.POST.get('membersTable_id_{}'.format(ordern),0))
                    except:
                        id = 0

                    dep = request.POST.get('membersTable_dep_{}'.format(ordern),'')
                    f = request.POST.get('membersTable_f_{}'.format(ordern),'')
                    i= request.POST.get('membersTable_i_{}'.format(ordern),'')
                    o = request.POST.get('membersTable_o_{}'.format(ordern),'')
                    fio = "{} {}{}{}{}".format(f,i[0:1],'.' if i!='' else '',o[0:1],'.' if o!='' else '')
                    dol = request.POST.get('membersTable_dol_{}'.format(ordern),'')
                    is_speaker = request.POST.get('membersTable_is_speaker_{}'.format(ordern),0)
                    is_init = request.POST.get('membersTable_is_init_{}'.format(ordern),0)
                    is_lead = request.POST.get('membersTable_is_lead_{}'.format(ordern),0)
                    is_presence = request.POST.get('membersTable_is_presence_{}'.format(ordern), 0)

                    if id:
                        #print('Update')
                        Member.objects.filter(id=id).update(dep=dep, f=f, i=i, o=o, dol=dol, fio = fio,
                                              is_speaker=is_speaker, is_lead=is_lead, is_init=is_init,
                                              meeting_id=meet_id, order_n=index, is_presence=is_presence)
                    else:
                        #print('Create')
                        id=Member.objects.create(dep=dep, f=f, i=i, o=o, dol=dol, fio = fio,
                                                 is_speaker=is_speaker, is_lead=is_lead, is_init=is_init,
                                                 meeting_id=meet_id, order_n=index, is_presence=is_presence).id
                    id_list.append(id)
                    #print(id, dep, f, i, o, dol, is_speaker, fio,meet_id, index)

            Member.objects.filter(meeting_id=meet_id).exclude(id__in=id_list).delete()

    response = HttpResponse()
    response['Content-Type'] = "text/javascript"
    response.write(json.dumps({'user':'admin','id':1,'result':res}))
    return response

@mb_login(url='login')
def members_get(request, meet_id=None):
    if request.is_ajax():
        members = Member.objects.filter(meeting__id=int(meet_id) if meet_id else 0).order_by('order_n').values()
        #data = serializers.serialize('json', list(members), fields=('dep','f','i','o','dol','is_speaker','Id'))
        data = json.dumps([dict(item) for item in members])
        return HttpResponse(data,'json')

    return meet_table(request)

@mb_login(url='login')
def members_doc(request, meet_id=None):
    try:
        meeting = Meeting.objects.get(id=meet_id)
    except:
        meeting = None

    if meeting:
        members = Member.objects.filter(meeting__id=int(meet_id) if meet_id else 0).order_by('order_n')

        deplist = [];  d = None; ml = [];
        for m in members:
            if (m.dep != d):
                if d: deplist.append({'name': d, 'members': ml})
                d = m.dep
                ml = []
            ml.append({'f': m.f, 'i': m.i, 'o': m.o, 'fio': m.fio, 'dep': m.dep, 'dol': m.dol})
        deplist.append({'name': d, 'members': ml})

        filename='meet{}_members_{}.docx'.format(meet_id,timezone.now().strftime('%Y%m%d%H%M%S'))
        fullname="media/{}".format(filename)
        doc = DocxTemplate("media/members_tpl.docx")
        context = {'meet_subj': meeting.meet_subj,
                   'meet_date':meeting.meet_date,
                   'deps':deplist}

        doc.render(context)
        doc.save(fullname)

        f = open(fullname, "rb")
        s = f.read()

meetings/templates/mt_meetform.html
{% extends "mb_main.html" %}
{% load staticfiles %}
{% load i18n %}

{% block content %}
<div class="container">

<h1 class="display-5">{% if meet_id %}Изменить{% else %}Новое{% endif %} совещание.</h1>

<form action="{% url 'meetings:update' meet_id %}" method="post">
    {% csrf_token %}

    <div class="form-row">
      <div class="form-group col-md-3">
        <label for="meetType">Тип совещания</label>
        <select class="form-control form-control-sm" id="meetType" name ="meetType" aria-describedby="meet_type_Help">
            {% for mtc in meeting_type_choices %}
                <option value="{{ mtc.0 }}" {% if mtc.0 == meet.meet_type %}selected{% endif %}>{{ mtc.1 }}</option>
            {% endfor %}
        </select>
      </div>

      <div class="form-group col-md-3">
            <label for="meetDate">Дата совещания:</label>
            <input type="text" class="form-control form-control-sm" id="meetDate" name="meetDate" data-date-format="dd.mm.yyyy" data-provide="datepicker" value="{{ meet.meet_date | date:"d.m.Y" }}" required>
            <div class="invalid-feedback">Пожалуйста, введите дату совещания.</div>
      </div>
      <div class="form-group col-md-3">
        <label for="meetStart">Начало:</label>
        <input type="text" class="form-control form-control-sm" id="meetStart" name="meetStart" value="{{ meet.meet_start }}">
      </div>
      <div class="form-group col-md-3">
        <label for="meetEnd">Конец:</label>
        <input type="text" class="form-control form-control-sm" id="meetEnd" name="meetEnd" value="{{ meet.meet_end }}">
      </div>
    </div>

    <div class="form-row">
      <div class="form-group col-md-12">
        <label for="meetSubj">Тема совещания:</label>
        <input type="text" class="form-control form-control-sm" id="meetSubj" name="meetSubj" placeholder="Введите тему планируемого совещания" value="{{ meet.meet_subj }}" required>
        <div class="invalid-feedback">Пожалуйста, введите тему совещания.</div>
      </div>
    </div>

<!--
    Адрес центральной студии не нужен, т.к. она первая в перечне студий!!!
    <div class="form-row">
      <div class="form-group col-md-12">
        <label for="meetPlace">Адрес студии:</label>
        <input type="text" class="form-control form-control-sm" id="meetPlace" name="meetPlace" placeholder="Введите планируемое место проведения совещаний" value="{{ meet.meet_place }}">
      </div>
    </div>
-->
<!--
    Информация о Ведущем не нужна, т.к. она выбирается в списке участников
    <div class="form-row">
      <div class="form-group col-md-12">
        <label for="meetLead">Ведущий совещания:</label>
        <input type="text" class="form-control form-control-sm" id="meetLead" name="meetLead" placeholder="Иванов Е.Н. - заместитель начальника Управления" aria-describedby="meetLead_Help" value="{{ meet.meet_lead }}">
        <small id="meetLead_Help" class="form-text text-muted">Введите информацию о ведущем совещания в формате Фамилия И.О. - должность.</small>
      </div>
    </div>
-->
    <div class="form-row">
<!--
      Информация об Инициаторе не нужна, т.к. она выбирается в списке участников
      <div class="form-group col-md-4">
        <label for="meetInit">Инициатор совещания:</label>
        <input type="text" class="form-control form-control-sm" id="meetInit" name="meetInit" placeholder="Козлов И.И." value="{{ meet.meet_init }}">
      </div>
-->
      <div class="form-group col-md-4">
        <label for="meetAcc">Ответственный за подготовку:</label>
        <input type="text" class="typeahead form-control form-control-sm" id="meetAcc" name="meetAcc" data-provide="typeahead" data-items="8" placeholder="Сидоров А.В." value="{{ meet.meet_acc }}" autocomplete="off">
      </div>
      <div class="form-group col-md-4">
        <label for="meetTel">Контактный телефон:</label>
        <input type="text" class="form-control form-control-sm" id="meetTel" name="meetTel" placeholder="(700) 2-22-22" value="{{ meet.meet_tel }}">
      </div>
      <div class="form-group col-md-4"></div>
    </div>

    <div class="form-row">
        <div class="form-check form-check-inline">
          <input class="form-check-input" type="checkbox" id="meetSave" name="meetSave" value="1" {% if meet.meet_save %}checked{% endif %}>
          <label class="form-check-label" for="meetSave">Необходима запись совещания</label>
        </div>
       <div class="form-check form-check-inline">
          <input class="form-check-input" type="radio" name="meetConfident" id="meetConfident1" value="0" {% if not meet.meet_confident %}checked{% endif %}>
          <label class="form-check-label" for="meetConfident1">Информация общего доступа</label>
        </div>
        <div class="form-check form-check-inline">
          <input class="form-check-input" type="radio" name="meetConfident" id="meetConfident2" value="1" {% if meet.meet_confident %}checked{% endif %}>
          <label class="form-check-label" for="meetConfident2">Коммерческая тайна</label>
        </div>
    </div>
    <br>
    <input type="hidden" id="omt_id" name="omt_id" value="{{ meet.id }}">
    <button type="submit" class="btn btn-primary"> {% if meet %}Сохранить{% else %}Создать{% endif %} совещание </button>
    <a role="button" class="btn btn-secondary" href="{% url 'meetings:table' %}" > Отмена </a>
</form>
</div>
{% endblock %}  {# content #}

{% block js-block %}
    <script src="{% static "js/bootstrap-datepicker.min.js" %}"></script>
    <script src="{% static "js/bootstrap-datepicker.ru.min.js" %}"></script>
    <script src="{% static "js/bootstrap-timepicker.min.js" %}"></script>
<script type="text/javascript">

    // Example starter JavaScript for disabling form submissions if there are invalid fields
    (function() {
      'use strict';
      window.addEventListener('load', function() {
        // Fetch all the forms we want to apply custom Bootstrap validation styles to
        var forms = document.getElementsByClassName('needs-validation');
        // Loop over them and prevent submission
        var validation = Array.prototype.filter.call(forms, function(form) {
          form.addEventListener('submit', function(event) {
            if (form.checkValidity() === false) {
              event.preventDefault();
              event.stopPropagation();
            }
            form.classList.add('was-validated');
          }, false);
        });
      }, false);
    })();

    $('#meetDate').datepicker({
        weekStart: 1,
        daysOfWeekHighlighted: "6,0",
        autoclose: true,
        todayHighlight: true,
        language: "ru",
    });
    $('#meetStart').timepicker({
                minuteStep: 1,
                appendWidgetTo: 'body',
                showSeconds: false,
                showMeridian: false,
                defaultTime: false,
                icons: {    up: 'fa fa-chevron-up',
                            down: 'fa fa-chevron-down'
                },
            });
    $('#meetEnd').timepicker({
                minuteStep: 1,
                appendWidgetTo: 'body',
                showSeconds: false,
                showMeridian: false,
                defaultTime: false,
                icons: {    up: 'fa fa-chevron-up',
                            down: 'fa fa-chevron-down'
                },
            });


var $inputEmployee = $("#meetAcc");

$inputEmployee.typeahead({
  source: [
          {% for e in employees %}{name:"{{ e.f }} {{ e.i }} {{ e.o }}",id:"{{ e.id }}", f:"{{ e.f }}", i:"{{ e.i }}", o:"{{ e.o }}", tel:"{{ e.tel }}"}{% if not forloop.last %},{% endif %}{% endfor %}
  ],
  autoSelect: true
});

$inputEmployee.change(function() {
  var current = $inputEmployee.typeahead("getActive");
  if (current) {
    // Some item from your model is active!
    $("#meetAcc").val(current.f+' '+current.i.substr(0,1)+'.'+current.o.substr(0,1)+'.');
    $("#meetTel").val(current.tel);
    if (current.name == $inputEmployee.val()) {
      // This means the exact match is found. Use toLowerCase() if you want case insensitive match.
    } else {
      // This means it is only a partial match, you can either add a new item
      // or take the active if you don't want new items
        // Выбор осещетсвлен из выпадающего списка по части строки
    }
  } else {
    // Nothing is active so it is a new value (or maybe empty value)
  }
});
</script>
{% endblock %}  {# js-block #}