meetboard/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings

from mb_auth.views import loginView, logoutView
from meetings.views import Home


urlpatterns = [
    path('', Home, name='home'),
    path('login/', loginView, name='login'),
    path('logout/', logoutView, name='logout'),
    path('meet/', include(('meetings.urls', 'meetings'), namespace='meetings')),
    path('proto/', include(('protocols.urls', 'protocols'), namespace='protocols')),
    path('admin/', admin.site.urls, name='admin'),
]

meetings/urls.py
from django.contrib import admin
from django.urls import path
from meetings import views

urlpatterns = [
    path('table/', views.meet_table, name='table'),
    path('add/', views.meet_update, name='add'),
    path('update/<str:meet_id>/', views.meet_update, name='update'),
    path('delete/<str:meet_id>/', views.meet_delete, name='delete'),
    path('copy/<str:meet_id>/', views.meet_copy, name='copy'),
    path('membersupd/', views.members_update, name='membersupd'),
    path('membersget/<str:meet_id>/', views.members_get, name='membersget'),
    path('membersdoc/<str:meet_id>/', views.members_doc, name='membersdoc'),
    path('itemsupd/', views.items_update, name='itemsupd'),
    path('itemsget/<str:meet_id>/', views.items_get, name='itemsget'),
    path('itemsdoc/<str:meet_id>/', views.items_doc, name='itemsdoc'),
    path('studiosupd/', views.studios_update, name='studiosupd'),
    path('studiosget/<str:meet_id>/', views.studios_get, name='studiosget'),
    path('studiosget_bydep/<str:dep_id>/', views.studios_get_bydep, name='studiosget_bydep'),
    path('studiosdoc/<str:meet_id>/', views.studios_doc, name='studiosdoc'),
    path('plandoc/', views.plan_doc, name='plandoc'),
    # path('checksget/<str:meet_id>/', views.checks_get, name='checksget'),
    path('checksupd/<str:meet_id>/', views.checks_update, name='checksupd'),
]

protocols/urls.py
from django.contrib import admin
from django.urls import path
from protocols import views

urlpatterns = [
    path('table/', views.proto_table, name='table'),
    path('table/<str:archive>/', views.proto_table, name='table'),
    path('add/', views.proto_update, name='add'),
    path('delete/<str:proto_id>/', views.proto_delete, name='delete'),
    path('update/<str:proto_id>/', views.proto_update, name='update'),
    path('update/<str:proto_id>/<int:meet_id>/', views.proto_update, name='update'),
    path('copy/<str:proto_id>/', views.proto_copy, name='copy'),
    path('decsupd/', views.decisions_update, name='decsupd'),
    path('decsget/<str:proto_id>/', views.decisions_get, name='decsget'),
    path('protodoc/<str:proto_id>/', views.proto_doc, name='doc'),
    path('check/<str:proto_id>/', views.proto_check, name='check'),
    path('checkupd/', views.check_update, name='checkupd'),
    path('decisions/<int:complete>/', views.dec_table, name='decisions'),
    path('decisions/', views.dec_table, name='decisions'),
    path('storecheck/', views.store_check, name='storecheck'),
]

protocols/models.py
from django.db import models
from django.utils import timezone

from meetings.models import Meeting

pSplit = 1
pItem = 0
fabula_prefix = 'СЛУШАЛИ: '
decisions_prefix = 'РЕШИЛИ: '

DECISIONS_TYPE_CHOICES = (
    (pItem, 'Пункт'),
    (pSplit,'Разделитель'),
)

# Create your models here.
class Protocol(models.Model):
    proto_header = models.CharField(max_length=256)
    proto_regdate = models.DateField(null=False, default=timezone.now, db_index=True)
    proto_regnum = models.CharField(max_length=16, null=True, db_index=True, blank=True)
    proto_place = models.CharField(max_length=32,null=True)
    proto_date = models.CharField(max_length=32, null=True)
    proto_preambula = models.TextField(blank=True)
    proto_fabula = models.TextField(blank=True)
    proto_fabula_prefix = models.CharField(max_length=32,default=fabula_prefix)
    proto_decisions_prefix = models.CharField(max_length=32,default=decisions_prefix)
    proto_fio = models.CharField(max_length=64, blank=True)
    proto_dol = models.CharField(max_length=128, blank=True)
    proto_off = models.IntegerField(default=0, db_index=True)
    meeting = models.OneToOneField(Meeting, null=True, on_delete=models.SET_NULL)

    class Meta:
        verbose_name = 'Протокол'
        verbose_name_plural = 'Протоколы'

    def __str__(self):
         return  self.proto_header

class Decision(models.Model):
    protocol = models.ForeignKey('Protocol', on_delete=models.CASCADE)
    dec_type = models.IntegerField(choices=DECISIONS_TYPE_CHOICES, default=pSplit, db_index=True)
    dec_text = models.TextField(blank=True)
    dec_term = models.CharField(max_length=20, blank=True, db_index=True)
    dec_date = models.DateField(null=True, db_index=True)
    dec_performers = models.CharField(max_length=256, blank=True)
    dec_progress = models.IntegerField(default=0)
    dec_comment = models.TextField(blank=True)
    order_n = models.PositiveIntegerField(null=False, default=0)

protocols/views.py
import datetime
import json
import os
import re

from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.db.models import Count, Avg, F, Q
from django.template.context_processors import csrf
from django.http import HttpResponse
from django.utils import timezone

from meetings.models import Meeting

from mb_auth.views import mb_login
from meetings.models import Employee
from protocols.models import DECISIONS_TYPE_CHOICES, pItem, fabula_prefix, decisions_prefix, Protocol, Decision
from docxtpl import DocxTemplate, RichText

# Create your views here.
@mb_login(url='login')
def proto_table(request, archive=None):
    if archive==None:
        try:
            archive = request.session['proto_archive']
        except:
            archive = 0

    try:
        archive = int(archive)
    except:
        archive = 0

    request.session['proto_archive'] = archive

    args={}
    args['employees'] = Employee.objects.all().order_by('f','i','o','dol')
    args['protocols'] = Protocol.objects.filter(proto_off=archive).\
        annotate(decisions_cnt=Count('decision')). \
        annotate(progress=Avg('decision__dec_progress',filter=Q(decision__dec_type=0))).\
        order_by('-proto_regdate','-proto_regnum')
    args['dec_type_choices'] = DECISIONS_TYPE_CHOICES

    args['proto_archive'] = archive

    return render(request,'pt_table.html', args)

@mb_login(url='login')
def proto_delete(request, proto_id=None):
    try:
        proto = Protocol.objects.get(id=proto_id)
    except:
        proto = None
    if proto:
        if proto.proto_off:
            proto.delete()
        else:
            proto.proto_off = 1
            proto.save()

    return redirect(reverse("protocols:table"))

@mb_login(url='login')
def proto_update(request, proto_id=None, meet_id=None):
    args={}
    args.update(csrf(request))
    proto =  None
    try:
        proto_id=int(proto_id)
    except:
        proto_id=0

    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        if request.POST:
            proto_header = request.POST.get('proto_header','')
            proto_regdate = request.POST.get('proto_regdate')
            proto_regdate = datetime.datetime.strptime(proto_regdate, '%d.%m.%Y').date()
            proto_regnum = request.POST.get('proto_regnum','')
            proto_place = request.POST.get('proto_place','')
            proto_date = request.POST.get('proto_date','')
            proto_preambula = request.POST.get('proto_preambula','')
            proto_fabula = request.POST.get('proto_fabula','')
            proto_fio = request.POST.get('proto_fio','')
            proto_dol = request.POST.get('proto_dol','')
            proto_fabula_prefix = request.POST.get('proto_fabula_prefix','')
            proto_decisions_prefix = request.POST.get('proto_decisions_prefix', '')
            proto_off = 1 if (request.POST.get('proto_off')) else 0
            try:
                meet_id = int(request.POST.get('proto_meet',None))
            except:
                meet_id = None

            if meet_id == 0:
                meet_id = None

            # Если произошло копирование протокола, то opt_id содержит ID старого совещания
            try:
                opt_id = request.POST.get('opt_id',0)
            except:
                opt_id=0

            if proto_id:
                print(meet_id)
                Protocol.objects.filter(id=proto_id).update(proto_header=proto_header,proto_regdate=proto_regdate,
                                                            proto_regnum=proto_regnum, proto_place=proto_place, proto_date=proto_date,
                                                            proto_preambula=proto_preambula, proto_fabula=proto_fabula,
                                                            proto_fio=proto_fio, proto_dol=proto_dol,
                                                            proto_fabula_prefix=proto_fabula_prefix, proto_decisions_prefix=proto_decisions_prefix,
                                                            proto_off=proto_off, meeting_id=meet_id)
            else:
                proto_id=Protocol.objects.create(proto_header=proto_header,proto_regdate=proto_regdate,
                                                        proto_regnum=proto_regnum, proto_place=proto_place, proto_date=proto_date,
                                                        proto_preambula=proto_preambula, proto_fabula=proto_fabula,
                                                        proto_fio=proto_fio, proto_dol=proto_dol,
                                                        proto_fabula_prefix=proto_fabula_prefix, proto_decisions_prefix=proto_decisions_prefix,
                                                        proto_off=proto_off, meeting_id=meet_id).id

            return redirect(reverse("protocols:table"))

    if proto_id:
        try:
            proto = Protocol.objects.get(id=proto_id)
        except Protocol.DoesNotExist:
            proto = None

    args['employees'] = Employee.objects.all().order_by('f', 'i', 'o').values('f', 'i', 'o','dol')
    args['proto']=proto
    args['fabula_prefix']=fabula_prefix
    args['decisions_prefix']=decisions_prefix
    args['proto_id'] = proto_id

    if meet_id:
        args['meet_id'] = meet_id
    elif proto:
        args['meet_id'] = proto.meeting.id if proto.meeting else 0
    else:
        args['meet_id'] = 0

    args['meet'] = Meeting.objects.filter(Q(protocol__meeting_id__isnull=True) | Q(id=args['meet_id'])).order_by('-meet_date')

    return render(request,'pt_protoform.html', args)


@mb_login(url='login')
def proto_copy(request, proto_id=None):
    args = {}
    opt =  None
    if proto_id:
        try:
            opt = Protocol.objects.get(id=int(proto_id))
        except Protocol.DoesNotExist:
            opt = None

    args['employees'] = Employee.objects.all().order_by('f', 'i', 'o').values('f', 'i', 'o', 'dol')
    args['proto']=opt
    args['proto_id'] = None

    args['fabula_prefix'] = fabula_prefix
    args['decisions_prefix'] = decisions_prefix
    args['meet_id'] = 0
    args['meet'] = Meeting.objects.filter(Q(protocol__meeting_id__isnull=True)).order_by('-meet_date')

    return render(request,'pt_protoform.html', args)

@mb_login(url='login')
def decisions_update(request):
    res = 1
    if request.method == 'POST':
        if request.POST:
            res = 0
            id_list = []
            proto_id = int(request.POST.get('proto_id',0))
            rowOrder = request.POST.get('decisionsTable_rowOrder',None)
            if rowOrder and proto_id:
                rowOrder = map(int, rowOrder.split(',')) if rowOrder else None
                for index, ordern in enumerate(rowOrder):
                    try:
                        id = int(request.POST.get('decisionsTable_id_{}'.format(ordern),0))
                    except:
                        id = 0

                    dec_performers = request.POST.get('decisionsTable_dec_performers_{}'.format(ordern),'')
                    dec_type = request.POST.get('decisionsTable_dec_type_{}'.format(ordern),'')
                    dec_text = request.POST.get('decisionsTable_dec_text_{}'.format(ordern),'')
                    dec_term = request.POST.get('decisionsTable_dec_term_{}'.format(ordern), '')
                    try:
                        dec_date = datetime.datetime.strptime(dec_term, "%d.%m.%Y").date()
                    except:
                        dec_date = None

                    if id:
                        Decision.objects.filter(id=id).update(dec_performers=dec_performers, dec_type=dec_type,
                                                              dec_text=dec_text, dec_term=dec_term, order_n=index,
                                                              protocol_id=proto_id, dec_date=dec_date)
                    else:
                        id=Decision.objects.create(dec_performers=dec_performers, dec_type=dec_type,
                                                   dec_text=dec_text, dec_term=dec_term, order_n=index,
                                                   protocol_id=proto_id, dec_date=dec_date).id
                    id_list.append(id)

                Decision.objects.filter(protocol_id=proto_id).exclude(id__in=id_list).delete()

    response = HttpResponse()
    response['Content-Type'] = "text/javascript"
    response.write(json.dumps({'user':'admin','id':1,'result':res}))
    return response

@mb_login(url='login')
def proto_doc(request, proto_id=None):
    proto_id = int(proto_id) if proto_id else 0
    try:
        protocol = Protocol.objects.get(id=proto_id)
    except:
        protocol = None

    if protocol:
        try: decisions = Decision.objects.filter(protocol__id=proto_id).order_by('order_n')
        except: decisions = []

        filename='protocol{}_{}.docx'.format(proto_id,timezone.now().strftime('%Y%m%d%H%M%S'))
        fullname="media/{}".format(filename)
        doc = DocxTemplate("media/protocol_tpl.docx")
        context = {'protocol': protocol,
                   'decisions': decisions,
                   'proto_header': RichText(protocol.proto_header,size=28,font='Times New Roman'),
                   'proto_preambula': RichText(protocol.proto_preambula,size=28,font='Times New Roman'),
                   'proto_fabula': RichText(protocol.proto_fabula,size=28,font='Times New Roman')
                   }
        doc.render(context)
        doc.save(fullname)

        f = open(fullname, "rb")
        s = f.read()
        response = HttpResponse()
        response["Content-Type"] = '{}; name="{}"'.format('application/msword', filename)
        response["Content-Disposition"] = 'attachment; filename="{}"'.format(filename)
        response["Content-Transfer-Encoding"] = 'binary'
        response["Content-Length"] = str(len(s))
        response.write(s)
        f.close()
        os.remove(fullname)

protocols/templates/pt_table.html
{% extends "mb_main.html" %}
{% load staticfiles %}
{% load i18n %}

{% block content %}
    <div class="row">
    <div class="col-sm-12">
        {% if proto_archive %}
            <h2>Архив протоколов (снятые с контроля).</h2>
        {% else %}
        <div class="btn-group" role="group" aria-label="protocols menu">
              <a type="button" class="btn btn-primary" href="{% url 'protocols:add' %}"><i class="fa fa-plus"></i> Создать протокол </a>
        </div>
        {% endif %}
    </div>
    </div>

    <br>

    <!-- ------------------------------------------- -->
    <!-- protocolDeleteModal ------------------------ -->
    <!-- ------------------------------------------- -->
    <div class="modal" id="protocolDeleteModal" tabindex="-1" role="dialog" aria-labelledby="protocolDeleteModalTitle" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="protocolDeleteModalTitle">
                {% if proto_archive %}
                    Удаление протокола
                {% else %}
                    Перемещение протокола в Архив
                {% endif %}
            </h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
              {% if proto_archive %}
                  Вы действительно хотите удалить протокол <b>"<span></span>"</b> ?
              {% else %}
                  Снять с контроля протокол <b>"<span></span>"</b>?
              {% endif %}
          </div>
          <div class="modal-footer">
            <a type="button" class="btn btn-secondary" data-dismiss="modal" href="#">Выйти</a>
            <a type="button" class="btn btn-primary" href="#" id="protocolDeleteButton">{% if proto_archive %}Удалить протокол{% else %}В Архив{% endif %}</a>
          </div>
        </div>
      </div>
    </div>

    <!-- ------------------------------------------- -->
    <!-- decsModal  -------------------------------- -->
    <!-- ------------------------------------------- -->
    <div class="modal decs-modal-lg" tabindex="-1" role="dialog" id="decsModal" data-backdrop="static" data-keyboard="false">
      <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
      <form action="{% url 'protocols:decsupd' %}" method="post" id="decisions_form">
      {% csrf_token %}
        <div class="modal-content">
          <div class="modal-header">
              <span class="modal-title">Решения в протокол</span>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>

          <div class="modal-body mx-auto">
              <table id="decisionsTable"> </table>
              <input type="hidden" name="proto_id" value="0" id="proto_id"/>
              <ul class="invalid-feedback" id="ulError"></ul>
          </div>
          <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
              <button type="submit" class="btn btn-primary" id="decsSave">Сохранить</button>
          </div>
        </div>
        </form>
      </div>
    </div>

    <!-- ------------------------------------------- -->
    <!-- protocolTable          ------------------------ -->
    <!-- ------------------------------------------- -->
    <table class="table table-sm table-hover display w-100" width="100%" id="protoTable">
      <thead>
        <tr>
          <th scope="col">Действия</th>
          <th scope="col">Дата</th>
          <th scope="col">Номер</th>
          <th scope="col">Название</th>
          <th scope="col">Решения</th>
          <th scope="col">Исполнение</th>
        </tr>
      </thead>
      <tbody>
      {% for p in protocols %}
        <tr>
          <th scope="row">
              <a href="#" data-toggle="tooltip" data-placement="top" title="Удалить протокол" onClick="$('#protocolDeleteButton').attr('href','{% url 'protocols:delete' p.id %}');$('#protocolDeleteModal').find('div.modal-body').find('span').text('{{ p.proto_header }}');$('#protocolDeleteModal').modal('show');"><i class="fa fa-trash"></i></a>
              <a href="{% url 'protocols:update' p.id %}" data-toggle="tooltip" data-placement="top" title="Изменить данные"><i class="fa fa-edit"></i></a>
              <a href="{% url 'protocols:copy' p.id %}" data-toggle="tooltip" data-placement="top" title="Скопировать"><i class="fa fa-copy"></i></a>
              <a href="{% url 'protocols:doc' p.id %}" data-toggle="tooltip" data-placement="top" title="Печать протокола"><i class="fa fa-print"></i></a>
          </th>
          <td>{{ p.proto_regdate | date:"d.m.Y" }}</td>
          <td {% if p.proto_regnum == '' %}class="table-warning"{% endif %}>{{ p.proto_regnum }}</td>
          <td {% if p.proto_header == '' %}class="table-warning"{% endif %}>{{ p.proto_header }}</td>
          <td {% if p.decs_cnt == 0 %}class="table-warning"{% endif %}>
              <a href="#" data-toggle="modal" data-target=".decs-modal-lg" data-proto="{{ p.id }}" data-header="{{ p.proto_header }}" data-dt="{{ p.proto_regdate }}">Решения</a>
           </td>
        <td>
              <a href="{% url 'protocols:check' p.id %}" data-toggle="tooltip" data-placement="top" title="Контроль"><!--<i class="fa fa-check-square"></i>-->
              <div class="progress">
                  <div class="progress-bar progress-bar-striped {% if p.progress < 50 %}bg-danger{% elif p.progress < 80 %}bg-warning{% elif p.progress < 100 %}bg-info{% else %}bg-success{% endif %}" role="progressbar" style="width: {{ p.progress|floatformat:'0' }}%" aria-valuenow="{{ p.progress|floatformat:'0' }}" aria-valuemin="0" aria-valuemax="100">{% if p.progress %}{{ p.progress|floatformat:'0' }}%{% endif %}</div>
              </div>
              </a>
        </td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
{% endblock %}  {# content #}

{% block js-block %}
<script type="text/javascript" src="{% static "js/jquery.tabledit.min.js" %}"></script>
<script type="text/javascript" src="{% static "appendGrid/jquery.appendGrid-1.7.1.min.js" %}"></script>
<script type="text/javascript" src="{% static "js/jquery.validate.min.js" %}"></script>

<script type="text/javascript">

////////////////////////////////////////////////////////////////
// protocolTable Settings and Functions
//
$(document).ready( function () {

    $('#protoTable').DataTable({
            ordering:  true,
            "language": {
                          "processing": "Подождите...",
                          "search": "Поиск:",
                          "lengthMenu": "Показать _MENU_ записей",
                          "info": "Записи с _START_ до _END_ из _TOTAL_ записей",
                          "infoEmpty": "Записи с 0 до 0 из 0 записей",
                          "infoFiltered": "(отфильтровано из _MAX_ записей)",
                          "infoPostFix": "",
                          "loadingRecords": "Загрузка записей...",
                          "zeroRecords": "Записи отсутствуют.",
                          "emptyTable": "В таблице отсутствуют данные",
                          "paginate": {
                            "first": "Первая",
                            "previous": "Предыдущая",
                            "next": "Следующая",
                            "last": "Последняя"
                          },
                          "aria": {
                            "sortAscending": ": активировать для сортировки столбца по возрастанию",
                            "sortDescending": ": активировать для сортировки столбца по убыванию"
                          }
                        }
        });
} );

////////////////////////////////////////////////////////////////
// decsModal Settings and Functions
//
$('#decsModal').on('show.bs.modal', function (event) {
    var button = $(event.relatedTarget); // Button that triggered the modal
    var proto = button.data('proto'); // Extract info from data-* attributes
    var header = button.data('header'); // Extract info from data-* attributes
    var dt = button.data('dt'); // Extract info from data-* attributes

    var modal = $('#decsModal');
    modal.find('.modal-title').html('Повестка совещания: <b>"' + header + '"</b><br>Дата совещания: <b>'+dt+'</b>');
    $('#proto_id').attr('value',proto);

    // Удаляем все данные таблицы
    while ($('#decisionsTable').appendGrid('getRowCount')>0)  {
      $('#decisionsTable').appendGrid('removeRow', 0);
    };

    // Очищаем информацию об ошибках
    $('#ulError').html('');

    // Загружаем данные из БД
    var request = $.ajax({
        url: "{% url 'protocols:decsget' -1 %}".replace('-1', proto),
        type: "POST",
        data: { csrfmiddlewaretoken: '{{ csrf_token }}' },
        dataType: "json",
        success: function(msg) {
            $('#decisionsTable').appendGrid('load', msg);
        }
    });

});

$(function () {
    $('#decisionsTable').appendGrid({caption: 'Решения в протокол',
        initRows: 0,
        columns: [
            { name: 'dec_type', display: 'Тип', type: 'select', ctrlClass: 'form-control form-control-sm', ctrlCss:{width:'120px'},
              ctrlOptions: {
                                {% for t in dec_type_choices %} {{ t.0 }} :'{{ t.1 }}' {% if not forloop.last %},{% endif %} {% endfor %}
                            }
            },
            { name: 'dec_performers', display: 'Исполнители', type: 'text', ctrlClass: 'form-control form-control-sm', ctrlCss:{width:'600px'}, ctrlAttr: { maxlength: 256 } },
            { name: 'dec_term', display: 'Срок', type: 'text', ctrlClass: 'form-control form-control-sm dec_term', ctrlCss:{width:'100px'}, ctrlAttr: { maxlength: 20} },
            { name: 'id', type: 'hidden', value: 0 },
        ],
        //customRowButtons: [
        //      { uiButton: { icon: 'ui-icon-person', showLabel: false }, click: selectEmployee, btnCss: { 'min-width': '30px' }, btnAttr: { title: 'Выбрать сотрудника' }, atTheFront: true },
        //],
        hideButtons: { insert: true },
        i18n: {
            append: 'Добавить запись',
            removeLast: 'Удалить последнюю запись',
            insert: 'Вставить запись',
            remove: 'Удалить запись',
            moveUp: 'Вверх',
            moveDown: 'Вниз',
        },
        useSubPanel: true,
        subPanelBuilder: function (cell, uniqueIndex) {
            // Create a label
            $('<span></span>').text('Решение: ').appendTo(cell);
            // Create a text area
            $('<textarea></textarea>').css('vertical-align', 'middle').attr({
                id: 'decisionsTable_dec_text_' + uniqueIndex,
                name: 'decisionsTable_dec_text_' + uniqueIndex,
                rows: 1, cols: 140,
                class: 'form-control form-control-sm'
            }).appendTo(cell);
        },
        subPanelGetter: function (uniqueIndex) {
            // Return the element value inside sub panel for `getAllValue` and `getRowValue` methods
            return { 'dec_text': $('#decisionsTable_dec_text_' + uniqueIndex).val() };
        },
        rowDataLoaded: function (caller, record, rowIndex, uniqueIndex) {
            // Check the record contains `item_subj`
            if (record.dec_text) {
                // Get the control in sub panel
                var elem = document.getElementById('decisionsTable_dec_text_' + uniqueIndex);
                // Fill the comment values in the sub panel
                elem.value = record.dec_text;
            }
        }
    });

    $('#decsSave').button();
    // Handle `Save` button click
    //$('#decsSave').button().click(function () {

    function decision_submit() {
        msg = $(document.forms[0]).serialize();
        action_url = $('#decisions_form').attr("action");

        $.ajax({
            type: 'POST',
            url: action_url,
            data: msg,
            success: function (data) {
            },
            error: function (xhr, str) {
            }
        });

        $('#decsModal').modal('hide');
        return true;
    };

    $.validator.addMethod('dec_term', function (value, element) {
        result_date = value.search(/^(0[1-9]|[12][0-9]|3[01])[- /.](0[1-9]|1[012])[- /.](19|20)\d\d$/) != -1 ;
        result_text = value.search(/^\D*$/) != -1;
        return result_date | result_text;
    }, 'В поле "Срок" необходимо ввести Дату в формате "ДД.ММ.ГГГ" либо любое слово, например "постоянно","еженедельно" и т.д.');

    // Initialize validation plugin
    $(document.forms[0]).validate({
        errorLabelContainer: '#ulError',
        wrapper: 'li',
        submitHandler: function () {
            decision_submit();
        }
    });
});
</script>
{% endblock %}