meetboard/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings

from mb_auth.views import loginView, logoutView
from meetings.views import Home


urlpatterns = [
    path('', Home, name='home'),
    path('login/', loginView, name='login'),
    path('logout/', logoutView, name='logout'),
    path('meet/', include(('meetings.urls', 'meetings'), namespace='meetings')),
    path('proto/', include(('protocols.urls', 'protocols'), namespace='protocols')),
    path('admin/', admin.site.urls, name='admin'),
]

meetings/urls.py
from django.contrib import admin
from django.urls import path
from meetings import views

urlpatterns = [
    path('table/', views.meet_table, name='table'),
    path('add/', views.meet_update, name='add'),
    path('update/<str:meet_id>/', views.meet_update, name='update'),
    path('delete/<str:meet_id>/', views.meet_delete, name='delete'),
    path('copy/<str:meet_id>/', views.meet_copy, name='copy'),
    path('membersupd/', views.members_update, name='membersupd'),
    path('membersget/<str:meet_id>/', views.members_get, name='membersget'),
    path('membersdoc/<str:meet_id>/', views.members_doc, name='membersdoc'),
    path('itemsupd/', views.items_update, name='itemsupd'),
    path('itemsget/<str:meet_id>/', views.items_get, name='itemsget'),
    path('itemsdoc/<str:meet_id>/', views.items_doc, name='itemsdoc'),
    path('studiosupd/', views.studios_update, name='studiosupd'),
    path('studiosget/<str:meet_id>/', views.studios_get, name='studiosget'),
    path('studiosget_bydep/<str:dep_id>/', views.studios_get_bydep, name='studiosget_bydep'),
    path('studiosdoc/<str:meet_id>/', views.studios_doc, name='studiosdoc'),
    path('plandoc/', views.plan_doc, name='plandoc'),
    # path('checksget/<str:meet_id>/', views.checks_get, name='checksget'),
    path('checksupd/<str:meet_id>/', views.checks_update, name='checksupd'),
]

protocols/urls.py
from django.contrib import admin
from django.urls import path
from protocols import views

urlpatterns = [
    path('table/', views.proto_table, name='table'),
    path('table/<str:archive>/', views.proto_table, name='table'),
    path('add/', views.proto_update, name='add'),
    path('delete/<str:proto_id>/', views.proto_delete, name='delete'),
    path('update/<str:proto_id>/', views.proto_update, name='update'),
    path('update/<str:proto_id>/<int:meet_id>/', views.proto_update, name='update'),
    path('copy/<str:proto_id>/', views.proto_copy, name='copy'),
    path('decsupd/', views.decisions_update, name='decsupd'),
    path('decsget/<str:proto_id>/', views.decisions_get, name='decsget'),
    path('protodoc/<str:proto_id>/', views.proto_doc, name='doc'),
    path('check/<str:proto_id>/', views.proto_check, name='check'),
    path('checkupd/', views.check_update, name='checkupd'),
    path('decisions/<int:complete>/', views.dec_table, name='decisions'),
    path('decisions/', views.dec_table, name='decisions'),
    path('storecheck/', views.store_check, name='storecheck'),
]

templates/extmenu.html
<li class="nav-item"><a class="nav-link" href="#" onclick="window.location  = 'http://' + window.location.hostname+':3000/';"><font color="white">Состав группы</font></a></li>
<li class="nav-item"><a class="nav-link" href="#" onclick="window.location  = 'http://' + window.location.hostname+':3000/vizovieag';"><font color="white">Документооборот</font></a></li>
<li class="nav-item"><a class="nav-link" href="#" onclick="window.location  = 'http://' + window.location.hostname+'/kanban';"><font color="white">Канбоард</font></a></li>
<li class="nav-item"><a class="nav-link" href="#" onclick="window.location  = 'http://' + window.location.hostname+':4848/hub';" ><font color="white">Аналитика</font></a></li>
<li class="nav-item"><a class="nav-link" href="#" onclick="window.location  = 'http://' + window.location.hostname+':3000/settings';"><font color="white">Настройки</font></a></li>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/mb_home.html
{% extends "mb_main.html" %}
{% load i18n %}

{% block main-content %}
      <!-- Main jumbotron for a primary marketing message or call to action -->
      <div class="jumbotron" style="padding: 1rem;">
        <div class="container">
          <h2 class="display-6">Система планирования совещаний и оформления протоколов</h2>
          <p>Система планирования совещаний поможет Вам организовать совещание шаг за шагом, оформить все необходимые документы и выполнить рассылку участникам совещаний.</p>
          <p>Система оформления протоколов поможет Вам быстро и безошибочно оформить любой протокол.</p>
          <hr class="my-4">
          <a class="btn btn-primary btn-lg" href="{% url 'meetings:table' %}" role="button">Начать работу с совещаниями &raquo;</a> &nbsp;&nbsp;
          <a class="btn btn-primary btn-lg" href="{% url 'protocols:table' %}" role="button">Начать работу с протоколами &raquo;</a>
        </div>
      </div>
{% endblock %}  {# content #}

templates/mb_login.html
{% extends "mb_main.html" %}

{% block content %}
<div class="container">

<div class='row'>
<div class="col-lg-3 col-md-2"></div>
<div class="col-lg-6 col-md-8 col-sm-12">
    <h1 class="display-5">Вход в систему.</h1>
    <form method="post" action='{% url "login" %}'>
    {% csrf_token %}
        <div class="form">
          <div class="form-group">
            <label for="inputUsername">Имя пользователя:</label>
            <input type="text" class="form-control" name="username" id="inputUsername" aria-describedby="usernameHelp" placeholder="Введите имя пользователя">
            <small id="emailHelp" class="form-text text-muted">Введите имя пользователя.</small>
          </div>

          <div class="form-group">
            <label for="inputPassword">Пароль:</label>
            <input type="password" class="form-control" name="password" id="inputPassword" placeholder="Password">
          </div>

          <button type="submit" class="btn btn-primary">Войти</button>
        </div>
    </form>
</div>
<div class="col-lg-3 col-md-2"></div>
</div>
</div>
<br>
{% endblock %}  {# content #}

templates/mb_main.html
{% load staticfiles %}
{% load cache %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Совещания</title>
    <link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.min.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "css/bootstrap-datepicker.min.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "css/bootstrap-timepicker.min.css" %}">
    <link rel="stylesheet" type="text/css"  href="{% static "css/jquery.dataTables.min.css" %}">
{#    <link rel="stylesheet" type="text/css"  href="{% static "bootstrap-slider/bootstrap-slider.min.css" %}">#}
    <link rel="stylesheet" href="{% static "fonts/css/all.css" %}">
    <link rel="stylesheet" type="text/css"  href="{% static "appendGrid/jquery-ui.structure.min.css" %}">
    <link rel="stylesheet" type="text/css"  href="{% static "appendGrid/jquery-ui.theme.min.css" %}">
    <link rel="stylesheet" type="text/css"  href="{% static "appendGrid/jquery.appendGrid-1.7.1.min.css" %}">
    <style>
        .modal-lg {
            max-width: 90% !important;
        }
        .slider.slider-horizontal .tooltip.tooltip-main.in,
        .slider.slider-vertical .tooltip.tooltip-main.in { opacity: 1 !important; }
    </style>
</head>
<body style="padding-top:60px;">
    <div class="container-fluid">
    <div class="row">
    <div class="col-sm-12">
    <nav class="navbar navbar-expand-md navbar-dark fixed-top" style="background-color: #0a76bf;">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarLeft" aria-controls="navbarLeft" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="{% url 'home' %}"><b>ПАО Газпром</b></a>

      <div class="collapse navbar-collapse" id="navbarLeft">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'meetings:table' %}">Совещания <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item dropdown active">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Протоколы <span class="sr-only">(current)</span></a>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="{% url 'protocols:table' 0 %}">На контроле</a>
              <a class="dropdown-item" href="{% url 'protocols:table' 1 %}">В Архиве</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'protocols:decisions' 2 %}">Все поручения</a>
              <a class="dropdown-item" href="{% url 'protocols:decisions' 4 %}">Все поручения (кроме бессрочных)</a>
              <a class="dropdown-item" href="{% url 'protocols:decisions' 0 %}">Невыполненные поручения</a>
              <a class="dropdown-item" href="{% url 'protocols:decisions' 3 %}">Просроченные поручения</a>
            </div>
          </li>
          {% include "extmenu.html" %}
        </ul>

        <ul class="navbar-nav mr-left">
          {% if mb_auth %}
              <li class="nav-item active">
            {% if user.is_authenticated %}
                <a class="nav-link" href="{% url "logout" %}"><i class="fa fa-torsos"></i>Выход ({{ user.username }})</a>
            {% else %}
                <a class="nav-link" href="{% url "login" %}"><i class="fa fa-torsos"></i>Вход</a>
            {% endif %}
              </li>
          {% endif %}

          {% if user.is_superuser or user.is_staff %}
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'admin:index' %}"><i class="fa fa-cogs"></i></a>
              </li>
          {% endif %}
         </ul>
      </div>
    </nav>

    {% if system_message %}
    <div class="alert {{ system_message.type }} alert-dismissible fade show" role="alert">
      <span>{{ system_message.text }}</span>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %}

    {% block content %}

    <main role="main">
      {% block main-content %}
      {% block body %} {% endblock %}  {# body #}
          <br>
      {% endblock %}  {# main-content #}

        <!-- Example row of columns -->
        <div class="row">
          {%  for meeting in meetings %}
              {%  if forloop.counter <= 3 %}
                  <div class="col-md-4">
                    <h5><b>Совещание {{ meeting.meet_date }}</b></h5>
                    <a href="{% url 'meetings:membersdoc' meeting.id %}" target='_blank' data-toggle="tooltip" data-placement="top" title="Формировать список участников" onClick=""><i class="fa fa-users"></i></a>
                    <a href="{% url 'meetings:itemsdoc' meeting.id %}" target='_blank' data-toggle="tooltip" data-placement="top" title="Формировать повестку" onClick=""><i class="fa fa-list"></i></a>
                    <a href="{% url 'meetings:studiosdoc' meeting.id %}" target='_blank' data-toggle="tooltip" data-placement="top" title="Формировать заявку" onClick=""><i class="fa fa-file"></i></a>
                    <a href="{% url 'meetings:checksupd' meeting.id %}" data-toggle="tooltip" data-placement="top" title="Контроль");"><!--<i class="fa fa-check-square"></i>-->
                      <div class="progress">
                          <div class="progress-bar progress-bar-striped {% if meeting.progress < 50 %}bg-danger{% elif meeting.progress < 80 %}bg-warning{% elif meeting.progress < 100 %}bg-info{% else %}bg-success{% endif %}" role="progressbar" style="width: {{ meeting.progress }}%" aria-valuenow="{{ meeting.complete }}" aria-valuemin="0" aria-valuemax="{{ meeting.total }}">{% if meeting.complete %}{{ meeting.progress }}%{% endif %}</div>
                      </div>
                    </a>
                    <p>
                        <b>Тема:</b> {{ meeting.meet_subj }}<br>
                        <b>Время:</b> {{ meeting.meet_start }}-{{ meeting.meet_end }}<br>
                        <b>Ответственный:</b> {{ meeting.meet_acc }}, {{ meeting.meet_tel }}<br>
                    </p>
                  </div>
              {% endif %}
          {% endfor %}
        </div>

        <hr>

    </main>

    {% endblock %}  {# content #}

    <hr class="my-3">
    <footer class="container">
      <p>&copy; ПАО Газпром 2018</p>
    </footer>
    </div> <!-- /container -->

{#    <script src="{% static "js/jquery-3.3.1.min.js" %}"></script>#}
    <script type="text/javascript" src="{% static "appendGrid/jquery-1.12.4.min.js" %}"></script>
    <script src="{% static "js/bootstrap.bundle.min.js" %}"></script>
    <script src="{% static "js/bootstrap3-typeahead.min.js" %}"></script>
    <script src="{% static "js/jquery.dataTables.min.js" %}"></script>
{#    <script src="{% static "bootstrap-slider/bootstrap-slider.min.js" %}"></script>#}
    <script type="text/javascript" src="{% static "appendGrid/jquery-ui-1.12.1.min.js" %}"></script>
    <script type="text/javascript">
    $(function () {
      $('[data-toggle="tooltip"]').tooltip()
    });

    </script>
    {% block js-block %}    {% endblock %}
</body>
</html>